backend:
  name: git-gateway
  repo: https://github.com/anav5704/Rosy-Hearts # Path to your Github repository
  branch: main # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "public/cakes" # Folder where user uploaded files should go
public_folder: "/cakes"

collections: # A list of collections the CMS should be able to edit
  - name: "cake" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Cake" # Used in the UI, e.g., "New Post"
    folder: "src/pages/cakes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Comment", name: "comment", widget: "string"}
      - {label: "Tags", name: "tags", widget: "select", options: ["classic", "seasonal", "league"]}
      - {label: "Price", name: "price", widget: "list", default: ["3 prices - small - medium large - seperated by commas (,)"]}
      - {label: "Ingredients", name: "ing", widget: "list", default: ["4 ingredients seperated by commas (,)"]}
      - {label: "Dietary Information", name: "diet", widget: "list", default: ["4 deitary facts seperated by commas (,)"]}
      - {label: "Layout", name: "layout", widget: "string", default: "../../layouts/CakePreview.astro"}    
