backend:
  name: github
  repo: https://github.com/anav5704/Rosy-Hearts # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "public/cakes" # Folder where user uploaded files should go
public_folder: "/cakes"

collections: # A list of collections the CMS should be able to edit
  - name: "cake" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Cake" # Used in the UI, e.g., "New Post"
    folder: "src/pages/cakes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    
    # slug: "{{slug}}"
    
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Comment", name: "comment", widget: "string"}
